# Copyright (c) 2026 kogeler
# SPDX-License-Identifier: MIT

"""Validate the four exact hash locks owned by root PEP 621 metadata."""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
LOCK_DEFINITIONS = (
    ("dev", "requirements-dev.txt"),
    ("test", "requirements-test.txt"),
    ("package", "requirements-package.txt"),
    ("docs", "requirements-docs.txt"),
)
LOCKS = tuple(filename for _group, filename in LOCK_DEFINITIONS)
BOOTSTRAP_PACKAGES = {
    "build",
    "click",
    "packaging",
    "pip",
    "pip-tools",
    "pyproject-hooks",
    "setuptools",
    "wheel",
}
PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;\\]+)\s+\\$")
HASH = re.compile(r"^--hash=sha256:([0-9a-f]{64})(?:\s+\\)?$")
DIRECT = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9._-]*)"
    r"(?:\[[A-Za-z0-9._-]+(?:,[A-Za-z0-9._-]+)*\])?==([^\s;]+)$"
)


class PolicyError(ValueError):
    """Dependency metadata violates the project contract."""


def normalize(name: str) -> str:
    """Normalize a Python distribution name according to PEP 503."""
    return re.sub(r"[-_.]+", "-", name).casefold()


def project_table(path: Path) -> dict[str, object]:
    """Load the root PEP 621 project table."""
    try:
        value = tomllib.loads(path.read_text(encoding="utf-8")).get("project")
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise PolicyError(f"cannot read {path}: {error}") from error
    if not isinstance(value, dict):
        raise PolicyError(f"{path}: missing [project] table")
    return value


def resolver_bootstrap(root: Path) -> dict[str, str]:
    """Read exact resolver bootstrap pins from their sole source owner."""
    path = root / "pyproject.toml"
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
        requirements = document["dependency-groups"]["resolver-bootstrap"]
    except (OSError, KeyError, TypeError, tomllib.TOMLDecodeError) as error:
        raise PolicyError(
            f"cannot read resolver bootstrap metadata: {error}"
        ) from error
    result = direct_requirements(
        requirements,
        source="pyproject.toml [dependency-groups].resolver-bootstrap",
    )
    if set(result) != BOOTSTRAP_PACKAGES:
        raise PolicyError(
            "resolver bootstrap must contain exactly: "
            + ", ".join(sorted(BOOTSTRAP_PACKAGES))
        )
    return result


def validate_resolver_bootstrap(root: Path) -> dict[str, str]:
    """Require bootstrap overlaps to equal the versions already frozen in locks."""
    bootstrap = resolver_bootstrap(root)
    locked: dict[str, set[str]] = {}
    for filename in LOCKS:
        for name, version in read_lock(root / filename).items():
            locked.setdefault(name, set()).add(version)
    missing = sorted((set(bootstrap) - {"pip-tools"}) - set(locked))
    if missing:
        raise PolicyError(
            "resolver bootstrap packages are absent from audience locks: "
            + ", ".join(missing)
        )
    mismatched = sorted(
        name
        for name, version in bootstrap.items()
        if name in locked and locked[name] != {version}
    )
    if mismatched:
        raise PolicyError(
            "resolver bootstrap versions differ from audience locks: "
            + ", ".join(mismatched)
        )
    return bootstrap


def direct_requirements(value: object, *, source: str) -> dict[str, str]:
    """Parse one non-empty array of exact direct dependency pins."""
    if (
        not isinstance(value, list)
        or not value
        or not all(isinstance(item, str) for item in value)
    ):
        raise PolicyError(
            f"{source}: dependencies must be a non-empty array of strings"
        )
    result: dict[str, str] = {}
    for requirement in value:
        match = DIRECT.fullmatch(requirement)
        if match is None:
            raise PolicyError(
                f"{source}: dependency is not one exact pin: {requirement}"
            )
        name = normalize(match.group(1))
        if name in result:
            raise PolicyError(f"{source}: duplicate direct dependency: {name}")
        result[name] = match.group(2)
    return result


def read_lock(path: Path) -> dict[str, str]:
    """Parse one generated hash lock and reject unsupported syntax."""
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as error:
        raise PolicyError(f"cannot read {path}: {error}") from error
    if "autogenerated by pip-compile" not in content:
        raise PolicyError(f"{path}: missing pip-compile header")

    pins: dict[str, str] = {}
    current: tuple[str, str] | None = None
    hashes: set[str] = set()

    def finish() -> None:
        nonlocal current, hashes
        if current is None:
            return
        name, version = current
        if not hashes:
            raise PolicyError(f"{path}: {name}=={version} has no SHA-256 hash")
        pins[name] = version
        current = None
        hashes = set()

    for line_number, line in enumerate(content.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line[:1].isspace():
            match = HASH.fullmatch(stripped)
            if match is None or current is None:
                raise PolicyError(f"{path}:{line_number}: unsupported continuation")
            if match.group(1) in hashes:
                raise PolicyError(f"{path}:{line_number}: duplicate SHA-256 hash")
            hashes.add(match.group(1))
            continue
        finish()
        match = PIN.fullmatch(line)
        if match is None:
            raise PolicyError(f"{path}:{line_number}: unsupported lock entry")
        name = normalize(match.group(1))
        if name in pins:
            raise PolicyError(f"{path}:{line_number}: duplicate package pin: {name}")
        current = (name, match.group(2))
    finish()
    if not pins:
        raise PolicyError(f"{path}: lock contains no pins")
    return pins


def lock_body(path: Path) -> str:
    """Return lock content without the interpreter-dependent generated header."""
    try:
        lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    except OSError as error:
        raise PolicyError(f"cannot read {path}: {error}") from error
    for index, line in enumerate(lines):
        if PIN.fullmatch(line.rstrip("\n")) is not None:
            return "".join(lines[index:])
    raise PolicyError(f"{path}: lock contains no pins")


def dependency_owners(root: Path) -> dict[str, tuple[dict[str, str], str]]:
    """Return exact direct pins and GitHub scope for all four audiences."""
    project = project_table(root / "pyproject.toml")
    if project.get("dependencies") != []:
        raise PolicyError("pyproject.toml: the runtime dependency array must be empty")
    optional = project.get("optional-dependencies")
    expected_groups = {group for group, _filename in LOCK_DEFINITIONS}
    if not isinstance(optional, dict) or set(optional) != expected_groups:
        raise PolicyError(
            "pyproject.toml: expected exactly the dev, test, package, and docs groups"
        )
    direct_by_group = {
        group: direct_requirements(
            optional[group],
            source=f"pyproject.toml [project.optional-dependencies].{group}",
        )
        for group in expected_groups
    }

    memberships: dict[str, list[tuple[str, str]]] = {}
    for group, direct in direct_by_group.items():
        for name, version in direct.items():
            memberships.setdefault(name, []).append((group, version))
    overlaps = {
        name: entries for name, entries in memberships.items() if len(entries) > 1
    }
    if overlaps:
        raise PolicyError(
            "direct dependency audiences must be disjoint: "
            + ", ".join(sorted(overlaps))
        )

    return {
        filename: (direct_by_group[group], "development")
        for group, filename in LOCK_DEFINITIONS
    }


def build_manifests(root: Path) -> dict[str, dict[str, object]]:
    """Validate all locks and build deterministic GitHub manifests."""
    manifests: dict[str, dict[str, object]] = {}
    for filename, (direct, scope) in dependency_owners(root).items():
        pins = read_lock(root / filename)
        missing = sorted(set(direct) - set(pins))
        if missing:
            raise PolicyError(f"{filename}: missing direct pins: {', '.join(missing)}")
        mismatched = sorted(name for name in direct if pins[name] != direct[name])
        if mismatched:
            details = ", ".join(
                f"{name}=={direct[name]} (lock has {pins[name]})" for name in mismatched
            )
            raise PolicyError(f"{filename}: direct versions differ: {details}")
        manifests[filename] = {
            "name": filename,
            "file": {"source_location": filename},
            "resolved": {
                name: {
                    "package_url": (
                        f"pkg:pypi/{quote(name, safe='')}@{quote(version, safe='')}"
                    ),
                    "relationship": "direct" if name in direct else "indirect",
                    "scope": scope,
                }
                for name, version in sorted(pins.items())
            },
        }
    return manifests


def compare_locks(root: Path, candidate_root: Path) -> None:
    """Compare every resolved pin and hash while ignoring only the header."""
    build_manifests(root)
    for filename in LOCKS:
        candidate = candidate_root / filename
        read_lock(candidate)
        if lock_body(root / filename) != lock_body(candidate):
            raise PolicyError(f"{filename}: regenerated pins or hashes differ")


def parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    value = argparse.ArgumentParser(description=__doc__)
    value.add_argument("--root", type=Path, default=ROOT)
    commands = value.add_subparsers(dest="command", required=True)
    commands.add_parser("validate", help="validate dependency owners and locks")
    commands.add_parser("bootstrap", help="print exact resolver bootstrap requirements")
    compare = commands.add_parser("compare", help="compare regenerated locks")
    compare.add_argument("--candidate-root", type=Path, required=True)
    return value


def run(arguments: argparse.Namespace) -> None:
    """Execute a validated dependency-policy command."""
    root = arguments.root.resolve()
    if arguments.command == "compare":
        compare_locks(root, arguments.candidate_root.resolve())
        print("Regenerated dependency pins and hashes match")
        return
    if arguments.command == "bootstrap":
        for name, version in validate_resolver_bootstrap(root).items():
            print(f"{name}=={version}")
        return
    manifests = build_manifests(root)
    validate_resolver_bootstrap(root)
    print(
        "Dependency locks validated: "
        + ", ".join(
            f"{name}={len(data['resolved'])}" for name, data in manifests.items()
        )
    )


def main() -> int:
    """Run the helper and return its process status."""
    try:
        run(parser().parse_args())
    except (OSError, PolicyError) as error:
        print(f"dependency policy error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
